### ISSUE TITLE
Example code missing console.log

### ISSUE THREAD

**Issue by wchang-546** [learn-co-curriculum/phase-1-js-fetch-on-demand-with-forms#8]
### Canvas Link

https://learning.flatironschool.com/courses/6460/assignments/243929?module_item_id=574388

### Concern

As I'm following along the source code, I think the final example is missing a console.log, so that the browser console produces the desired data. If I implement the source code, nothing is output in the console. 

### Suggested Changes

My proposed fix is below. 

fetch(`http://localhost:3000/movies/${input.value}`)
                .then((response) => response.json())
                .then((data) => {
                    const title = document.querySelector("section#movieDetails h4");
                    const summary = document.querySelector("section#movieDetails p");

                    title.innerText = data.title;
                    summary.innerText = data.summary;
                    **console.log(data);**
                });

**Comment by DavidWolff218** [comment]
Hello!

Thank you for reaching out. It's important to remember that console.log is only there to help us as developers understand what the data is that we are working with. If you look at the previous code it has you implement as seen below, you will note that we already had you console.log the data variable.

inputForm.addEventListener("submit", (event) => {
  event.preventDefault();
  const input = document.querySelector("input#searchByID");

  fetch(`http://localhost:3000/movies/${input.value}`)
    .then((response) => response.json())
    .then((data) => {
      console.log(data);
    });
});

The code that you posted is the next step in the process where you are then using that data to populate the page. By the time that information is rendering on the DOM, we really don't need to see what the data variable is anymore, as we have already completed our task using it.
Hope that all makes sense!
